# Generated by Django 4.0.3 on 2022-03-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payables',
            name='codigo_barra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payables',
            name='status_pago',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('partial_paid', 'Pago parcial')], default='pending', max_length=25),
        ),
    ]
